version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: expense-tracker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: expense_tracker
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: expense-tracker-app
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "7077:7077"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expense_tracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql-data: